# generated by datamodel-codegen:
#   filename:  domain-services.v1.yaml

from __future__ import annotations

from datetime import date
from typing import Annotated, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, Field


class Problem(BaseModel):
    type: Annotated[str, Field(description="RFC 9457: absent means about:blank.")] = "about:blank"
    title: str
    status: int
    detail: str | None = None
    instance: Annotated[
        str | None,
        Field(
            description="RFC 9457: the request path. It can carry ids or a pincode, so never log it."
        ),
    ] = None
    code: Annotated[
        str,
        Field(
            description="Machine-readable error code; the table in the API description lists them."
        ),
    ]
    field: Annotated[
        str | None,
        Field(
            description="QUOTE_OUT_OF_BOUNDS only. The request member outside the product's limits."
        ),
    ] = None
    allowed_min: Annotated[
        str | None,
        Field(
            description="QUOTE_OUT_OF_BOUNDS only. The lowest allowed value, as a decimal string."
        ),
    ] = None
    allowed_max: Annotated[
        str | None,
        Field(
            description="QUOTE_OUT_OF_BOUNDS only. The highest allowed value, as a decimal string; absent when unbounded."
        ),
    ] = None
    allowed_step: Annotated[
        str | None,
        Field(description="QUOTE_OUT_OF_BOUNDS on cover only. Cover must be a multiple of this."),
    ] = None


type Money = Annotated[
    str, Field(description="Rupees as a decimal string.", pattern="^\\d+(\\.\\d{1,2})?$")
]


type SignedMoney = Annotated[
    str,
    Field(
        description="Rupees as a decimal string that may be negative.",
        pattern="^-?\\d+(\\.\\d{1,2})?$",
    ),
]


type Sha256Hex = Annotated[str, Field(pattern="^[0-9a-f]{64}$")]


type Uin = Annotated[
    str,
    Field(
        description="IRDAI unique identification number, e.g. 999N001V02 (product) or 999A007V01 (rider).",
        pattern="^[0-9]{3}[A-Z][0-9]{3}V[0-9]{2}$",
    ),
]


type Pincode = Annotated[str, Field(pattern="^[1-9][0-9]{5}$")]


class Pins(BaseModel):
    rules: Annotated[str, Field(description="DMN release pinned for the session.")]


type Gender = Literal["male", "female", "transgender"]


type ProductType = Literal["TERM", "TERM_ROP", "NON_PAR_SAVINGS", "PAR", "ULIP"]


class Versions(BaseModel):
    rules_version: str
    params_version: str
    ranker_version: str
    registry_version: str
    rating_version: str
    active_rules_versions: Annotated[
        list[str], Field(description="Every rules version a session may still be pinned to.")
    ]


class ConsentNotice(BaseModel):
    notice_version: Annotated[str, Field(examples=["2026.09.1-en"])]
    language: str
    body: str
    body_sha256: Sha256Hex
    is_dummy: bool


type PurposeId = Literal["P1_NEEDS_RECO", "P2_ADVISOR_CONTACT", "P3_MARKETING"]


class PurposeGrant(BaseModel):
    purpose_id: PurposeId
    granted: bool


type ConsentMethod = Annotated[
    Literal["structured_action", "parsed_affirmation"],
    Field(
        description="How consent was captured. TDD §3.5 says typed_affirmation; the DDL (§7.2) says parsed_affirmation, which is used everywhere."
    ),
]


class ConsentRecordCreate(BaseModel):
    session_id: UUID
    subject_ref: Annotated[UUID, Field(description="Pseudonymous subject reference.")]
    notice_version: str
    notice_sha256: Sha256Hex
    language: Annotated[str, Field(description="The language the notice was shown in.")]
    ai_disclosure_version: str
    purposes: list[PurposeGrant]
    age_18_plus_declared: bool
    method: ConsentMethod


class ConsentRecord(BaseModel):
    consent_id: UUID
    notice_version: str
    notice_sha256: Sha256Hex
    notice_language: str
    ai_disclosure_version: str
    purposes: Annotated[
        list[PurposeGrant],
        Field(
            description="Current state, one grant per purpose. The history stays in the domain tier."
        ),
    ]
    age_18_plus_declared: bool
    method: ConsentMethod
    captured_at: Annotated[AwareDatetime, Field(description="Server clock, UTC.")]
    withdrawn_at: AwareDatetime | None = None
    valid_p1: Annotated[
        bool,
        Field(
            description="P1 granted, not withdrawn, 18+ declared, notice not superseded and within the consent TTL, as of the request's as_of."
        ),
    ]
    valid_reasons: Annotated[
        list[str],
        Field(
            description="Why valid_p1 is false; empty when it is true. Codes: P1_NOT_GRANTED, WITHDRAWN, AGE_NOT_DECLARED, NOTICE_SUPERSEDED (a newer notice is in force for the language) and CONSENT_EXPIRED (older than the consent TTL). The last two send a resumed session back to S0."
        ),
    ]


class ConsentWithdrawal(BaseModel):
    reason: str | None = None


type ProductStatus = Literal["in_force", "withdrawn"]


type PptOption = Annotated[
    Literal["regular", "limited_10", "single"], Field(description="Premium-paying term option.")
]


class Rider(BaseModel):
    uin: Uin
    name: str
    attaches_to: Annotated[list[Uin], Field(description="Base product UINs.")]
    sa_max_inr: Money | None
    is_dummy: bool


class ProductDocument(BaseModel):
    kind: Literal["CIS", "BI", "POLICY_WORDING"]
    version: str
    language: str
    uri: str
    sha256: Sha256Hex


class KillSwitch(BaseModel):
    reason: str
    actor: str


class KillSwitchResult(BaseModel):
    uin: Uin
    status: ProductStatus


class DisclosureItem(BaseModel):
    disclosure_id: Annotated[str, Field(examples=["DISC-GLOBAL-SOLICIT-01"])]
    body: Annotated[str, Field(description="Verbatim approved text.")]
    body_sha256: Sha256Hex


class DisclosureSet(BaseModel):
    uin: Uin
    channel: str
    language: str
    registry_version: str
    items: Annotated[list[DisclosureItem], Field(description="In the order they must be shown.")]
    set_sha256: Sha256Hex
    is_dummy: bool


class Disclosure(BaseModel):
    disclosure_id: str
    language: str
    body: Annotated[str, Field(description="Verbatim approved text.")]
    body_sha256: Sha256Hex
    is_dummy: bool


class PincodeInfo(BaseModel):
    pincode: Pincode
    district: str
    state: str
    serviceable: bool
    is_dummy: bool


class Occupation(BaseModel):
    code: str
    label: str
    risk_class: Annotated[int, Field(ge=1, le=4)]
    is_dummy: bool


class RequiredAttribute(BaseModel):
    attribute: Annotated[str, Field(examples=["gender"])]
    reason_line_id: Annotated[str, Field(description="Approved one-line reason for asking.")]
    asked_if: Annotated[
        str | None,
        Field(description="Condition for asking, e.g. only when the rating basis uses gender."),
    ] = None


type Residency = Literal["resident", "nri", "oci_pio"]


class Proposer(BaseModel):
    is_life_assured: bool
    relationship: Annotated[
        str | None, Field(description="Proposer's relationship to the life assured.")
    ] = None
    la_age: Annotated[int | None, Field(description="Age of the life assured.", ge=0)] = None
    business_cover: bool | None = None


class EligibilityRequest(BaseModel):
    pins: Pins
    age_years: Annotated[
        int,
        Field(
            description="Not bounded to 18–75 here: the engine itself routes under-18 (E-03) and over-65 (E-04).",
            ge=0,
        ),
    ]
    dob: date | None = None
    gender: Gender | None = None
    residency: Residency
    pincode: Pincode
    tobacco_12m: Annotated[
        bool | None, Field(description="null means the customer declined to answer.")
    ]
    occupation_code: Annotated[
        str | None,
        Field(description="Occupation master code; null when declined or unknown (E-06)."),
    ]
    health_flags: Annotated[
        dict[str, bool | None],
        Field(description="Screening question id to answer; null means declined."),
    ]
    proposer: Proposer


class EligibilityResult(BaseModel):
    decision_id: UUID
    outcome: Literal["ELIGIBLE", "NOT_ELIGIBLE", "HUMAN_ESCALATION", "DATA_ERASURE_EXIT", "RE_ASK"]
    eligible_uins: list[Uin]
    uw_path: Literal["standard", "manual"]
    flags: list[str]
    escalation_reason: str | None = None
    rule_ids: Annotated[list[str], Field(description="Rules that fired.")]
    reason_codes: list[str]
    rules_version: str
    params_version: str
    inputs_sha256: Sha256Hex


class RequiredSlot(BaseModel):
    slot: str
    weight: Annotated[float, Field(ge=0.0)]
    reason_line_id: str


type Goal = Annotated[
    Literal["income_protection", "loan_cover", "child_education", "retirement", "savings"],
    Field(description="Ranked goals slot (TDD §3.7 slot table)."),
]


type IncomeType = Annotated[
    Literal["salaried", "self_employed", "homemaker", "student", "retired"],
    Field(description="Income type slot (TDD §3.7 slot table)."),
]


type RiskProfile = Annotated[
    Literal["conservative", "moderate", "aggressive"],
    Field(description="Savings goals only; unused while phase 1 launches term plans only."),
]


class Dependant(BaseModel):
    relation: Literal["spouse", "child", "parent", "other"]
    age: Annotated[int, Field(ge=0, le=110)]


class Liability(BaseModel):
    kind: Literal["home", "vehicle", "education", "personal", "business", "other"]
    outstanding_inr: Money
    years_left: Annotated[int, Field(ge=0, le=40)]


class NeedsPayload(BaseModel):
    goals: Annotated[list[Goal], Field(description="Ranked.")]
    annual_income_inr: Annotated[
        Money | None, Field(description="null means the customer declined to answer.")
    ]
    income_type: IncomeType
    dependants: Annotated[list[Dependant], Field(validate_default=True)] = []
    liabilities: Annotated[list[Liability], Field(validate_default=True)] = []
    existing_cover_inr: Annotated[str, Field(pattern="^\\d+(\\.\\d{1,2})?$")] = "0"
    employer_cover_inr: Annotated[
        str, Field(description="Counted per underwriting rules.", pattern="^\\d+(\\.\\d{1,2})?$")
    ] = "0"
    earmarked_assets_inr: Money | None = None
    premium_budget_inr_pa: Money | None = None
    cover_to_age: Annotated[int, Field(ge=40, le=85)] = 60
    risk_profile: RiskProfile | None = None
    horizon_years: int | None = None
    confirmed_at: AwareDatetime | None = None
    slots_sha256: Annotated[
        Sha256Hex | None,
        Field(description="Bound at confirmation (I2). Excluded from the inputs_sha256 preimage."),
    ] = None
    existing_annual_premium_inr: Annotated[
        Money, Field(description="Premiums already paid on existing policies, for affordability.")
    ]
    financial_distress: Annotated[
        bool, Field(description="Stated financial distress (vulnerability).")
    ]
    comprehension_difficulty_count: Annotated[
        int, Field(description="Repeated comprehension difficulty (vulnerability).", ge=0)
    ]


class EligibilitySnapshot(BaseModel):
    age_years: Annotated[int, Field(ge=0)]
    tobacco_12m: Annotated[
        bool | None, Field(description="null means the customer declined to answer.")
    ]
    gender: Gender | None = None
    eligible_uins: list[Uin]
    flags: list[str]


class SuitabilityRequest(BaseModel):
    pins: Pins
    eligibility: EligibilitySnapshot
    needs: NeedsPayload


type Rate = Annotated[
    str, Field(description="A decimal fraction, e.g. 0.07 for 7%.", pattern="^\\d+(\\.\\d+)?$")
]


class SuitabilityAssumptions(BaseModel):
    cover_to_age: int
    dependency_years: Annotated[int, Field(description="The n of the income term.", ge=0)]
    discount_rate: Rate
    income_growth: Rate
    consumption_share: Rate
    final_expenses_inr: Money
    existing_cover_counted_inr: Annotated[
        Money,
        Field(
            description="Individual cover plus the share of employer cover the parameters count."
        ),
    ]


class SuitabilityResult(BaseModel):
    decision_id: UUID
    outcome: Annotated[
        Literal["FIT", "NO_GAP", "ESCALATE"],
        Field(description="NO_GAP is the need <= 0 case, which exits to advisory."),
    ]
    escalation_reason: str | None = None
    profile_sufficiency: Annotated[
        float,
        Field(
            description="Weighted share of S2 slots answered; S3 needs 0.7 or an explicit election.",
            ge=0.0,
            le=1.0,
        ),
    ]
    affordability_premium_estimate_inr: Money | None = None
    fit_types: list[ProductType]
    excluded: Annotated[
        dict[ProductType, list[str]], Field(description="Product type to reason codes.")
    ]
    need_inr: Annotated[
        SignedMoney,
        Field(description="The computed need N; zero or negative when existing cover suffices."),
    ]
    recommended_cover_inr: Money
    uw_cap_inr: Annotated[Money | None, Field(description="null when income was declined.")]
    term_years: int
    affordability: Literal["green", "amber", "red", "unknown"]
    vulnerability_flags: list[str]
    assumptions: SuitabilityAssumptions
    rule_ids: Annotated[list[str], Field(description="Rules that fired.")]
    reason_codes: list[str]
    params_version: Annotated[str, Field(description="Actuarial assumptions.")]
    rules_version: str
    inputs_sha256: Annotated[
        Sha256Hex,
        Field(
            description="SHA-256(JCS(needs without slots_sha256)); must equal needs.slots_sha256 (I2)."
        ),
    ]


class RankingRequest(BaseModel):
    pins: Pins
    eligible_uins: list[Uin]
    suitability: SuitabilityResult
    excluded_uins: Annotated[
        list[Uin], Field(description="Withdrawn or kill-switched products to leave out.")
    ]
    channel: str
    language: str
    as_of: AwareDatetime
    tobacco_12m: bool | None
    gender: Gender | None = None
    age_years: Annotated[int, Field(description="The life assured's age.", ge=0)]
    flags: Annotated[
        list[str],
        Field(
            description="The S1 eligibility flags. PREMIUM_WITHHELD (a declined health or tobacco answer) withholds every premium."
        ),
    ]


type Frequency = Literal["annual", "half_yearly", "monthly", "single"]


class QuoteRequest(BaseModel):
    pins: Pins
    uin: Uin
    sum_assured_inr: Money
    term_years: Annotated[int, Field(ge=1)]
    ppt: PptOption
    rider_uins: list[Uin]
    age_years: Annotated[int, Field(ge=0)]
    gender: Gender | None = None
    tobacco_12m: Annotated[
        bool | None,
        Field(
            description="null (declined) is answered 422 TOBACCO_UNDISCLOSED; premiums are withheld upstream."
        ),
    ]
    frequency: Frequency


class PremiumQuote(BaseModel):
    decision_id: UUID
    quote_id: Annotated[str, Field(examples=["Q-2026-09-20-0042"])]
    uin: Uin
    sum_assured_inr: Annotated[Money, Field(description="The cover this quote priced.")]
    term_years: Annotated[int, Field(description="The policy term this quote priced.")]
    ppt: PptOption
    annual_premium_inr: Annotated[
        Money,
        Field(
            description="The base premium plus every rider premium, GST included. With ppt single it is the single premium."
        ),
    ]
    frequency: Frequency
    valid_until: date
    indicative: Annotated[
        bool,
        Field(
            description="Always true; the final premium is set after underwriting. TDD §3.8 types it Literal[True], but openapi-generator 7.25 cannot compile a boolean const or enum."
        ),
    ]
    rider_premiums: Annotated[
        dict[str, Money],
        Field(
            description="Rider UIN to its annual premium, GST included; part of annual_premium_inr."
        ),
    ]
    gst_included: bool
    rating_version: str
    inputs_sha256: Sha256Hex
    reason_codes: list[str]


class QuoteAlternativesRequest(BaseModel):
    pins: Pins
    uin: Uin
    sum_assured_inr: Money
    term_years: Annotated[int, Field(ge=1)]
    ppt: PptOption
    rider_uins: list[Uin]
    age_years: Annotated[int, Field(ge=0)]
    gender: Gender | None = None
    tobacco_12m: Annotated[
        bool | None,
        Field(
            description="null (declined) is answered 422 TOBACCO_UNDISCLOSED; premiums are withheld upstream."
        ),
    ]
    frequency: Frequency
    recommended_cover_inr: Money


class QuoteAlternative(BaseModel):
    quote: PremiumQuote
    protection_gap_inr: Money
    change: Literal["LOWER_COVER", "FEWER_RIDERS", "OTHER_PPT"]


class Product(BaseModel):
    uin: Uin
    name: str
    category: ProductType
    status: ProductStatus
    entry_age_min: int
    entry_age_max: int
    maturity_age_max: int
    sa_min_inr: Money
    sa_max_inr: Money | None
    term_years_min: Annotated[int, Field(description="Lower bound of catalog.product.term_years.")]
    term_years_max: Annotated[int, Field(description="Upper bound of catalog.product.term_years.")]
    ppt_options: list[PptOption]
    benefit_payment_options: Annotated[
        list[str],
        Field(
            description="How the benefit is paid, e.g. lumpsum or monthly_income (catalog.product.payout_options, renamed so the contract carries no payout field)."
        ),
    ]
    rider_uins: list[Uin]
    effective_from: date
    effective_to: date | None
    launch_enabled: bool
    is_dummy: bool
    riders: list[Rider]
    documents: list[ProductDocument]


class RecommendedOption(BaseModel):
    rank: Annotated[int, Field(ge=1, le=3)]
    uin: Uin
    sum_assured_inr: Money
    term_years: int
    ppt_years: int
    rider_uins: list[Uin] = []
    quote: Annotated[
        PremiumQuote | None,
        Field(description="null when health or tobacco answers were declined, or rating is down."),
    ]
    reason_codes: list[str]
    protection_gap_inr: Annotated[str, Field(pattern="^\\d+(\\.\\d{1,2})?$")] = "0"


class RankingResult(BaseModel):
    decision_id: UUID
    options: Annotated[
        list[RecommendedOption],
        Field(
            description="At most three. Empty, with reason code NO_ELIGIBLE_OPTION, when nothing qualifies; the orchestrator then escalates.",
            max_length=3,
        ),
    ]
    ranker_version: str
    suitability_inputs_sha256: Annotated[
        Sha256Hex, Field(description="Must match the SuitabilityResult it ranked (I2).")
    ]
    inputs_sha256: Sha256Hex
    reason_codes: list[str]
