/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open a session. Its version pins are fixed for its life. */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Erase the session (consent withdrawal, I5).
         * @description The same turn as the `ERASE` action: the consent is withdrawn and the session's data erased. The body is the released confirmation. Afterwards the session is gone, so a repeat is 401. The Idempotency-Key is optional here.
         */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send one customer turn (text or a structured action); returns the released turn. */
        post: operations["postTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The session's server-sent events while turns run. */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /** @constant */
            type: "about:blank";
            /** @description The HTTP reason phrase. */
            title: string;
            status: number;
            /**
             * @description Machine-readable; the table in the API description says when each is sent.
             * @enum {string}
             */
            code: "BAD_REQUEST" | "UNAUTHORIZED" | "NOT_FOUND" | "METHOD_NOT_ALLOWED" | "SESSION_BUSY" | "SESSION_EXPIRED" | "REQUEST_ENTITY_TOO_LARGE" | "RATE_LIMITED" | "INTERNAL_SERVER_ERROR" | "BAD_GATEWAY" | "SERVICE_UNAVAILABLE";
        };
        /** @description Rupees as a decimal string. */
        Money: string;
        Sha256Hex: string;
        /** @description IRDAI unique identification number, e.g. 999N001V02 (product) or 999A007V01 (rider). */
        Uin: string;
        /** @enum {string} */
        Locale: "en-IN" | "hi-IN";
        /**
         * @description Premium-paying term option.
         * @enum {string}
         */
        PptOption: "regular" | "limited_10" | "single";
        /** @enum {string} */
        DocumentKind: "CIS" | "BI" | "POLICY_WORDING";
        /**
         * @description The conversation state after the turn. HUMAN_ESCALATION, EXIT, EXIT_ADVISORY, DATA_ERASURE and HANDOFF are closed: the session takes no further journey.
         * @enum {string}
         */
        FsmState: "S0" | "S1" | "QUOTE_ONLY" | "S2" | "S3" | "HUMAN_ESCALATION" | "PAUSE" | "EXIT" | "EXIT_ADVISORY" | "DATA_ERASURE" | "HANDOFF";
        CreateSessionRequest: {
            /** @enum {string} */
            channel: "web" | "app";
            locale: components["schemas"]["Locale"];
        };
        CreatedSession: {
            /** Format: uuid */
            session_id: string;
            /** @description The session's bearer token. Shown once; the server keeps only its hash. */
            session_token: string;
            /** @description The session's event stream, relative to the API base. */
            events_url: string;
        };
        /** @description Exactly one of `text` and `action`. */
        TurnRequest: components["schemas"]["TextTurn"] | components["schemas"]["ActionTurn"];
        TextTurn: {
            /** @description What the customer typed. */
            text: string;
        };
        ActionTurn: {
            action: components["schemas"]["Action"];
        };
        /** @description A structured action: what a quick reply or a form sends. The state that takes each type is named on its schema. */
        Action: components["schemas"]["SimpleAction"] | components["schemas"]["NoticeLanguageAction"] | components["schemas"]["LanguageAction"] | components["schemas"]["ConsentSubmitAction"] | components["schemas"]["IntentAction"] | components["schemas"]["SlotAction"] | components["schemas"]["ReaskAction"] | components["schemas"]["ConfirmAction"] | components["schemas"]["FactAction"] | components["schemas"]["PeriodAction"] | components["schemas"]["ElectAction"] | components["schemas"]["ApplyAction"] | components["schemas"]["CheaperAction"] | components["schemas"]["DisclosureAckAction"] | components["schemas"]["AdvisorContactAction"];
        EmptyPayload: Record<string, never>;
        /**
         * @description Actions without a payload.
         *     - `START`: open the chat (S0): the greeting, the AI disclosure, the notice and the consent form.
         *     - `RETRY`: try again after a dependency outage (any state).
         *     - `CONTINUE`: carry on with the open prompt (any state).
         *     - `HUMAN_REQUEST`: ask for a person (any state after S0; Human Escalation).
         *     - `ERASE`: withdraw consent and erase the session (any state; as `DELETE /v1/sessions/{id}`).
         *     - `OPT_IN`, `SATISFIED`: after a Quote-Only quote, get advice or stop there.
         *     - `REVISE`, `SAVE`, `REJECT_ALL`: S3's choices (`SAVE` elsewhere asks for time and pauses).
         *     - `END`: end the conversation (S1, Quote-Only, S2, S3).
         */
        SimpleAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "START" | "RETRY" | "CONTINUE" | "HUMAN_REQUEST" | "ERASE" | "OPT_IN" | "SATISFIED" | "REVISE" | "SAVE" | "REJECT_ALL" | "END";
            payload: components["schemas"]["EmptyPayload"];
        };
        /** @description S0. Show the consent notice in another language. */
        NoticeLanguageAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "NOTICE_LANGUAGE";
            payload: {
                language: components["schemas"]["Locale"];
            };
        };
        /** @description Any state. Continue the conversation in another language. */
        LanguageAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "LANGUAGE";
            payload: {
                locale: components["schemas"]["Locale"];
            };
        };
        /** @description S0. The consent form: every purpose ticked or not, the 18+ box, and the notice the form named (`form.notice_version` and `form.notice_sha256`). */
        ConsentSubmitAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "CONSENT_SUBMIT";
            payload: {
                purposes: {
                    /** @description Needs assessment and recommendation (required to go on). */
                    P1: boolean;
                    /** @description A licensed advisor may contact the customer. */
                    P2: boolean;
                    /** @description Product updates. */
                    P3: boolean;
                };
                age_18_plus: boolean;
                notice_version: string;
                notice_sha256: components["schemas"]["Sha256Hex"];
            };
        };
        /** @description S0. One of the four intent quick replies. */
        IntentAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "INTENT";
            payload: {
                /** @enum {string} */
                intent: "new_purchase" | "specific_plan" | "existing_policy" | "general_faq";
            };
        };
        /** @description S1, Quote-Only, S2. An answer to the open question, as its quick reply offered it (S2's goals may come as a ranked list). */
        SlotAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "SLOT";
            payload: {
                slot: string;
                /** @description The value the quick reply carries. */
                value: string | number | boolean | unknown[];
            };
        };
        /** @description S1, Quote-Only, S2. Ask a question again, to correct its answer. */
        ReaskAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "REASK";
            payload: {
                slot: string;
            };
        };
        /** @description S1, Quote-Only, S2. Yes or no to a read-back, a summary or an offer. */
        ConfirmAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "CONFIRM";
            payload: {
                confirmed: boolean;
            };
        };
        /** @description After a side question. The customer's answer to a fact the answer proposed (the tax regime). */
        FactAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "FACT";
            payload: {
                /** @constant */
                slot: "tax_regime";
                /** @enum {string} */
                value: "old" | "new";
                confirmed: boolean;
            };
        };
        /** @description S2. Whether an amount said with "k" was a month or a year. */
        PeriodAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "PERIOD";
            payload: {
                /** @enum {string} */
                period: "month" | "year";
            };
        };
        /** @description S2. Go on to options with a partial profile, or answer more questions. */
        ElectAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ELECT";
            payload: {
                elected: boolean;
            };
        };
        /** @description S3. Choose a plan to apply for: as offered (only `uin`), or with the customer's own cover, term, premium-paying term or riders (priced for exactly that). Without `uin` and with several options, the options are offered again. */
        ApplyAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "APPLY";
            payload: {
                uin?: components["schemas"]["Uin"];
                sum_assured_inr?: components["schemas"]["Money"];
                term_years?: number;
                ppt?: components["schemas"]["PptOption"];
                rider_uins?: components["schemas"]["Uin"][];
            };
        };
        /** @description S3. Lower-premium alternatives for one option. */
        CheaperAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "CHEAPER";
            payload: {
                uin: components["schemas"]["Uin"];
            };
        };
        /** @description S3. The customer acknowledges the disclosures and documents shown for the chosen plan. Send the payload of the quick reply exactly as received: the hashes bind the acknowledgment to what was shown. */
        DisclosureAckAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "DISCLOSURE_ACK";
            payload: {
                uin: components["schemas"]["Uin"];
                registry_version: string;
                disclosure_set_sha256: components["schemas"]["Sha256Hex"];
                document_sha256: components["schemas"]["DocumentHashes"];
            };
        };
        /** @description Human Escalation. Grant (or not) the P2 purpose, so an advisor may contact the customer. */
        AdvisorContactAction: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ADVISOR_CONTACT";
            payload: {
                granted: boolean;
            };
        };
        TurnResponse: {
            /**
             * Format: uuid
             * @description The customer turn this answers.
             */
            turn_id: string;
            state: components["schemas"]["FsmState"];
            message: components["schemas"]["Message"];
            /** @description Per plan shown, the newest version of each document (CIS, policy wording, BI). */
            documents: components["schemas"]["DocumentsShown"][];
        };
        /** @description A release blocked by the output rails is the release-blocked template and the advisor offer in `text`, with every list empty and `form` null. */
        Message: {
            /** @description The whole reply; the parts' texts joined by blank lines. */
            text: string;
            parts: components["schemas"]["Part"][];
            /** @description Each evidence ([E#]) or engine ([R#]) handle cited, and what it refers to. */
            citations: components["schemas"]["Citation"][];
            /** @description One per cited chunk, in first-cited order. */
            sources: components["schemas"]["Source"][];
            /** @description Per plan presented, the hash of the registry disclosure set shown (I4). */
            disclosures: components["schemas"]["DisclosureShown"][];
            /** @description Always null. The call to action is sent as the `cta` part and the quick replies. */
            cta: null;
            /** @description S0's consent form while the consent prompt is open; otherwise null. */
            form: components["schemas"]["ConsentForm"] | null;
            quick_replies: components["schemas"]["QuickReply"][];
        };
        Part: {
            id: components["schemas"]["PartId"];
            text: string;
        };
        /** @description Where a part's text comes from. Each branch's title names a namespace. */
        PartId: string | ("generated:narrative" | "generated:answer") | ("needs_recap" | "comparison" | "why_it_fits" | "cta" | "sources");
        Citation: {
            handle: string;
            /** @description The evidence chunk id */
            ref: string;
        };
        Source: {
            title: string;
            section: string;
            version: string;
            /** Format: date */
            effective_from: string;
            /** @description Where the source document lives (a repository path in the DUMMY corpus). */
            uri: string;
        };
        DisclosureShown: {
            uin: components["schemas"]["Uin"];
            set_sha256: components["schemas"]["Sha256Hex"];
        };
        /** @description Document kind -> the SHA-256 of the version shown. */
        DocumentHashes: {
            [key: string]: components["schemas"]["Sha256Hex"];
        };
        DocumentsShown: {
            uin: components["schemas"]["Uin"];
            documents: components["schemas"]["DocumentHashes"];
        };
        /** @description Rendered as a form; it is submitted as the `CONSENT_SUBMIT` action. */
        ConsentForm: {
            /** @constant */
            type: "CONSENT_SUBMIT";
            notice_version: string;
            notice_sha256: components["schemas"]["Sha256Hex"];
            language: components["schemas"]["Locale"];
            purposes: {
                /** @enum {string} */
                id: "P1" | "P2" | "P3";
                label: string;
                required: boolean;
            }[];
            adult: {
                label: string;
            };
            /** @description The submit button's label. */
            submit: string;
        };
        QuickReply: {
            label: string;
            action: components["schemas"]["Action"];
        };
        TurnStatusEvent: {
            /** Format: uuid */
            turn_id: string;
            /** @enum {string} */
            status: "analysing" | "composing" | "validating";
        };
    };
    responses: {
        /** @description The released turn, as RFC 8785 (JCS) bytes. */
        Released: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["TurnResponse"];
            };
        };
        /** @description A malformed or invalid request. Nothing of the request is echoed. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"] & {
                    /** @constant */
                    status?: 400;
                    /** @constant */
                    code?: "BAD_REQUEST";
                };
            };
        };
        /** @description No token, a wrong one, an unknown or an erased session. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"] & {
                    /** @constant */
                    status?: 401;
                    /** @constant */
                    code?: "UNAUTHORIZED";
                };
            };
        };
        /** @description Another turn of this session is running. */
        SessionBusy: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"] & {
                    /** @constant */
                    status?: 409;
                    /** @constant */
                    code?: "SESSION_BUSY";
                };
            };
        };
        /** @description The session passed its time to live. */
        SessionExpired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"] & {
                    /** @constant */
                    status?: 410;
                    /** @constant */
                    code?: "SESSION_EXPIRED";
                };
            };
        };
        /** @description The request body is over 16 KiB. */
        TooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"] & {
                    /** @constant */
                    status?: 413;
                    /** @constant */
                    code?: "REQUEST_ENTITY_TOO_LARGE";
                };
            };
        };
        /** @description Too many turns from this customer in a window. */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"] & {
                    /** @constant */
                    status?: 429;
                    /** @constant */
                    code?: "RATE_LIMITED";
                };
            };
        };
        /** @description A defect. Nothing was released. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"] & {
                    /** @constant */
                    status?: 500;
                    /** @constant */
                    code?: "INTERNAL_SERVER_ERROR";
                };
            };
        };
        /** @description The domain tier refused a reference read. */
        BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"] & {
                    /** @constant */
                    status?: 502;
                    /** @constant */
                    code?: "BAD_GATEWAY";
                };
            };
        };
        /** @description A dependency is down. Nothing was released; a retry with the same key is safe. */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"] & {
                    /** @constant */
                    status?: 503;
                    /** @constant */
                    code?: "SERVICE_UNAVAILABLE";
                };
            };
        };
    };
    parameters: {
        SessionId: string;
        /** @description A UUID per turn. A retry with the same key replays the released turn. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedSession"];
                };
            };
            400: components["responses"]["BadRequest"];
            413: components["responses"]["TooLarge"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["Unavailable"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Released"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["SessionBusy"];
            410: components["responses"]["SessionExpired"];
            413: components["responses"]["TooLarge"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    postTurn: {
        parameters: {
            query?: never;
            header: {
                /** @description A UUID per turn. A retry with the same key replays the released turn. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnRequest"];
            };
        };
        responses: {
            200: components["responses"]["Released"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["SessionBusy"];
            410: components["responses"]["SessionExpired"];
            413: components["responses"]["TooLarge"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A text/event-stream that stays open. Each event is `event: <name>` and `data: <JSON>`; `x-events` maps each name to its data schema. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            410: components["responses"]["SessionExpired"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["Unavailable"];
        };
    };
}
